  
apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  finalizers:
    - imageregistry.operator.openshift.io/finalizer
  name: cluster
spec:
  storage:
    managementState: Managed
    s3:
      bucket: cluster-znxjs-9s78v-image-registry-ap-southeast-1-okbwesaibyca
      encrypt: true
      region: ap-southeast-1
      virtualHostedStyle: false