apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amq-stream-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  labels:
    gitops.ownedBy: cluster-config  
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: /amq-streams-operator/operator/overlays/amq-streams-2.1.x
    repoURL: 'https://github.com/davidgaulin/tmp-gitops-catalog.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2 
        maxDuration: 3m 