apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  labels:
    gitops.ownedBy: cluster-config  
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: openshift-pipelines-operator/overlays/1.7/
    repoURL: 'https://github.com/davidgaulin/tmp-gitops-catalog.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2 
        maxDuration: 3m 
