apiVersion: v1
kind: ResourceQuota
metadata:
 name: project-quota
spec:
  hard:
    pods: "100" 
    requests.cpu: "8" 
    requests.memory: 24Gi 
    limits.cpu: "12" 
    limits.memory: 32Gi
    requests.storage: "200G"