apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ircc-integration-amq-broker-address-application
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    gitops.ownedBy: cluster-config  
spec:
  destination:
    namespace: ircc-integration-amq-broker
    server: 'https://kubernetes.default.svc'
  project: ircc-integration-amq-broker-address
  source:
    path: address
    repoURL: 'https://github.com/davidgaulin/tmp-ircc-integration-amq-broker-address.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2 
        maxDuration: 3m 
