kind: Namespace
apiVersion: v1
metadata:
  name: ircc-integration-amq-streams
  labels:
    ircc.gc.ca/environment: dev
    ircc.gc.ca/team: ircc-integration
    argocd.argoproj.io/managed-by: ircc-tenant-integration-gitops    
spec: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-same-namespace
  namespace: ircc-integration-amq-streams
spec:
  ingress:
  - from:
    - podSelector: {}
  podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-ingress
  namespace: ircc-integration-amq-streams
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-by-default
  namespace: ircc-integration-amq-streams
spec:
  ingress: []
  podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-monitoring
  namespace: ircc-integration-amq-streams
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: monitoring
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: v1
kind: "LimitRange"
metadata:
  name: project-limits
  namespace: ircc-integration-amq-streams
spec:
  limits:
    - type: "Container"
      default:
        cpu: "1" 
        memory: "1Gi" 
      defaultRequest:
        cpu: "500m" 
        memory: "500Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: project-quota
  namespace: ircc-integration-amq-streams
spec:
  hard:
    pods: "30" 
    requests.cpu: "32" 
    requests.memory: 64Gi 
    limits.cpu: "32" 
    limits.memory: 64Gi
    requests.storage: "200Gi"
