kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ircc-integration-elasticsearch-eck

resources:
- ircc-integration-elasticsearch-eck.yaml
- ircc-integration-elasticsearch-eck-quotas.yaml
- limit-range.yaml

# TODO - 808849 - We need to figure out why standard network policy are breaking this setup
# Once 808849 is complete, the configuration below should do the trick


# bases:
# - ../../../../../components/app/namespaces/large

# resources:
# - ircc-integration-elasticsearch-eck.yaml

# Quota adjustment required - To be revisited on usage
# patches:
# - target:
#     kind: ResourceQuota
#     name: project-quota
#   patch: |-
#     - op: replace
#       path: /spec/hard/requests.cpu
#       value: 18
#     - op: replace
#       path: /spec/hard/limits.cpu
#       value: 24
#     - op: replace
#       path: /spec/hard/limits.memory
#       value: 64Gi