kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: amq-broker-console
  namespace: ircc-integration-amq-broker
spec:
  host: dev.broker-ui.apps.cluster1.hip-pih-development.aws.ci.gc.ca
  to:
    kind: Service
    name: ircc-amq-broker-hdls-svc
    weight: 100
  port:
    targetPort: console-jolokia
  tls:
    termination: edge
    key: |-
      -----BEGIN CERTIFICATE-----
      MIIDvzCCAqegAwIBAgIQTKUptTTfXrSWtAPC9A4/QDANBgkqhkiG9w0BAQsFADBo
      MQswCQYDVQQGEwJDQTENMAsGA1UECgwESVJDQzEMMAoGA1UECwwDQVdTMRAwDgYD
      VQQIDAdPbnRhcmlvMRkwFwYDVQQDDBBJUkNDIFBCTU0gUm9vdENBMQ8wDQYDVQQH
      DAZPdHRhd2EwHhcNMjAwOTE1MTEwNDM1WhcNMzAwOTE0MTIwNDM1WjBnMQswCQYD
      VQQGEwJDQTENMAsGA1UECgwESVJDQzEMMAoGA1UECwwDQVdTMRAwDgYDVQQIDAdP
      bnRhcmlvMRgwFgYDVQQDDA9JUkNDIFBCTU0gU3ViQ0ExDzANBgNVBAcMBk90dGF3
      YTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALhUBWvtuYylrCJi5SWR
      +kExaAKlFdiXnnusZP4fb3ZE+gz4VTFDZ7Wf1IAZF7H17GQthhTP3lvCHKtnyvtn
      lL6wcjMxokmMa/r6iibFRUqlPkcLBSQYLAH3sCUIjVojwEXJBSGXB6kmNNyP3NTM
      eagS2vGTu77D7rvcEYu/jmnd/4ENn6hYEWQh5Mp2TVIv1kh0vn7edFXCeUgy0SHC
      7qdV7J/WC9OuZBsm05FO5C1KJn1new3PiXE/NuY/FvSISR0fZZXnFHFjrZKFzv/3
      wF/4b4QEGMUb/BmGQgfqVxElnczfEJ2MhjeIKL1tU5bGm8ZgjpQfSuuwEOh88+gA
      rgcCAwEAAaNmMGQwEgYDVR0TAQH/BAgwBgEB/wIBADAfBgNVHSMEGDAWgBS11oB5
      ACP6g9uGW1kp2eBF79aETzAdBgNVHQ4EFgQUaycXq92FS3KZLgL7HalqhFGrAKAw
      DgYDVR0PAQH/BAQDAgGGMA0GCSqGSIb3DQEBCwUAA4IBAQB7N2lTSR7FGWOTsnSy
      PNJUdeZ1VAGIZMUC/XaHZUGNmereR+T1h63koN7sPBnlvhJ72JNSHRhmctZiOpF9
      Q3rRIqyAiTA+REnn99477BYe36X9M/+seCZtM/Isl1SJbqyjv0kcw1uR/DQDkS/R
      CGQLwqTlyoYwRm13TiZE0g/gOtV65HDm2rNxD21VCbt8hFIg8L5QWzxNUyEikm1E
      3IsKxtJ8bHEEym5R3rYSqWBNfkAJMEcs3/1Yq/WxhbMymBIRi8ReRgchu9NcSux1
      7oF9cWwgi1YOgaeXxD9JtpEu8xMfOY/gORcE1zDRBM8XioacNgQEbskUcaYCDVz5
      Vewg
      -----END CERTIFICATE-----
    caCertificate: |-
      -----BEGIN CERTIFICATE-----
      MIIDnDCCAoSgAwIBAgIQJ94IvUg0vDk7AHIPcrFmtzANBgkqhkiG9w0BAQsFADBo
      MQswCQYDVQQGEwJDQTENMAsGA1UECgwESVJDQzEMMAoGA1UECwwDQVdTMRAwDgYD
      VQQIDAdPbnRhcmlvMRkwFwYDVQQDDBBJUkNDIFBCTU0gUm9vdENBMQ8wDQYDVQQH
      DAZPdHRhd2EwHhcNMjAwOTE0MTg1MDIwWhcNMzAwOTE0MTk1MDIwWjBoMQswCQYD
      VQQGEwJDQTENMAsGA1UECgwESVJDQzEMMAoGA1UECwwDQVdTMRAwDgYDVQQIDAdP
      bnRhcmlvMRkwFwYDVQQDDBBJUkNDIFBCTU0gUm9vdENBMQ8wDQYDVQQHDAZPdHRh
      d2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQColKSxT0JNSySNLdK0
      tb8tUX2xFdcP4y9v5nlimTZkZbisXXgZyWbZ2h8oKkxLUQE6vJrfRB34pZ74kYKE
      g2jPEdqyF7JsrreqEmx46pyYb5inWjCBuXFNarSbupkUpmdGTf6CX60lxAHuxrJG
      igBlL8lshYrQPd5c3mG+EcIYZe8tqrR7NgvxnAWHxktnyVFW7ucin9j8ZOKl4E0F
      M3sveJk5scox9OkDYdTRPWRQjJ5VVUjkQuGYSJHp33vgWfQuA2eWFr+2vqBNtjIj
      Ek1grCfAlEZKq9FL8EMpXELiXqOtKhtdm9yKDFcyjUYAUbyVB9/hEdQFtapCEzBh
      Mqb/AgMBAAGjQjBAMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLXWgHkAI/qD
      24ZbWSnZ4EXv1oRPMA4GA1UdDwEB/wQEAwIBhjANBgkqhkiG9w0BAQsFAAOCAQEA
      h0WJ8CF6bWO/z4jv574p5nDszG1STYfGIEm7i+6OTmjZ9nb8sgxVJ3z6n2lFkRH0
      UnI+mvP0MRWXOEuCDPnfkfqUDuAnrqDYRGlbTd78qbnxWNUNnB9NDcN4UCCvl3rj
      HUA+0sQ+Tv8nmrGlJU3Z0n+LMK5CB5EXIj+6DrEtrfut3x/Ne06ShinpQ4sh/gfu
      oHQ6Ie2Oi9oVMvUXNyADi0/6vqkzEb/L5fknsJPc4GbLE6MMrjKEV5DQ7nTmTVlU
      FsL5YmLqV9BE1UtPYH95hE2UZTFm6QNhx+zDUXgbZ73t13t5RkEHzLzRWttz+KWx
      3wsKnpY+xuwibxaYtH+sVA==
      -----END CERTIFICATE-----
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None