kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
- ../../../../../../components/argocd/apps/operators/amq-broker/base

resources:
- role-binding-developers-group.yaml
- amq-broker-route.yaml


