kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- github.com/redhat-cop/gitops-catalog.git/amq-streams-operator/operator/overlays/amq-streams-2.1.x

patches:
- target:
    kind: Subscription
    name: amq-streams
  patch: |-
    - op: replace
      path: /spec/channel
      value: 'amq-streams-2.1.x'