kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
- ../00-base/

resources:
  - 01-namespaces

patches:
- target:
    kind: Application
    name: journeylab-family-class-application
  patch: |-
    - op: replace
      path: /spec/source/path
      value: journeylab-family-class/environment/dev