apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config-infra-machineset
  namespace: openshift-gitops
spec:
  source:
    path: environments/dev/app/cluster-config/overlays/registry