kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ircc-integration-poc/
- ircc-integration-testing/
- ircc-integration-pipeline/

# Sandboxes
- ircc-integration-cumulus-namespace-added-role.yaml

# TODO Confirm what this namespace is for and if it should be in base
- ircc-integration/
