kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- int-pr-fc-cumulus-namespace-added-role.yaml
- int-sandbox-constant-carmai/
- int-sandbox-daniel-taylor/
- int-sandbox-elgin-jessica/
- int-sandbox-jovovic-stefan/
- int-sandbox-kanumuri-subbarao/
- int-sandbox-kirnishni-vladimir/
- int-sandbox-langevin-yves/
- int-sandbox-ma-matthew/
- int-sandbox-mantha-gerry/
- int-sandbox-navid-mahesaniya/
- int-sandbox-prevost-michel/
- int-sandbox-richard-philip/
- int-sandbox-slim-rayan/
- ircc-integration/
- ircc-integration-poc/
- ircc-integration-testing/
