kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ircc-hip-sandbox-tang-patrick

bases:
- ../../../../../../components/app/namespaces/small

resources:
- ircc-hip-sandbox-tang-patrick.yaml

