apiVersion: v1
kind: "LimitRange"
metadata:
  name: project-limits
spec:
  limits:
    - type: "Container"
      default:
        cpu: "1" 
        memory: "1Gi" 
      defaultRequest:
        cpu: "500m" 
        memory: "500Mi"