apiVersion: v1
kind: ResourceQuota
metadata:
 name: project-quota
 namespace: int-pr-fc-cumulus
spec:
  hard:
    pods: "30" 
    requests.cpu: "8" 
    requests.memory: 24Gi 
    limits.cpu: "12" 
    limits.memory: 32Gi
    requests.storage: "200G"