apiVersion: v1
kind: ResourceQuota
metadata:
 name: project-quota
spec:
  hard:
    pods: "60" 
    requests.cpu: "4" 
    requests.memory: 10Gi 
    limits.cpu: "8" 
    limits.memory: 20Gi
    requests.storage: "100G"