kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
- ../00-base/

resources:
  - 01-namespaces

# Patching the argocd application from base to point to dev
patches:
- target:
    kind: Application
    name: ircc-integration-cumulus-application
  patch: |-
    - op: replace
      path: /spec/source/path
      value: ircc-integration-cumulus/environment/dev
