kind: Namespace
apiVersion: v1
metadata:
  name: journeylab-family-class
  labels:
    ircc.gc.ca/environment: dev
    ircc.gc.ca/team: journeylab
    # TODO Move to environment layer
    argocd.argoproj.io/managed-by: tenant-journeylab-gitops 
spec: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: journeylab-family-class
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: Developers
