apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  finalizers:
    - imageregistry.operator.openshift.io/finalizer

  name: cluster
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          namespaces:
          - openshift-image-registry
          topologyKey: kubernetes.io/hostname
        weight: 100
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra
    operator: Exists
  logLevel: Normal
  rolloutStrategy: RollingUpdate
  operatorLogLevel: Normal
  requests:
    read:
      maxWaitInQueue: 0s
    write:
      maxWaitInQueue: 0s
  observedConfig: null
  managementState: Managed
  proxy: {}
  unsupportedConfigOverrides: null
  httpSecret: 9c2b5cb0ee34f2a2eeabe3fbb584a38????
  storage:
    managementState: Managed
    s3:
      bucket: cluster-znxjs-9s78v-image-registry-ap-southeast-1-okbwesaibyca
      encrypt: true
      region: ap-southeast-1
      virtualHostedStyle: false
  replicas: 3