kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
- ../../../../../../components/app/cluster-config/infra-machineset/base

patchesStrategicMerge:
- infra-machineset-zone1.yaml
- infra-machineset-zone2.yaml
- infra-machineset-zone3.yaml