
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: tenant-integration-gitops
  namespace: tenant-integration-gitops
spec:
  rbac:
    defaultPolicy: role:readonly
    policy: |
      g, openshift-gitops-admins, role:admin
    scopes: "[groups]"
