apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  labels:
    gitops.ownedBy: cluster-config
  name: ircc-tenant-journeylab-gitops
  namespace: openshift-gitops
spec:
  destination:
    namespace: ircc-tenant-journeylab-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: tenants/journeylab/01-dev/
    repoURL: https://github.com/filiy/gitops-test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5