apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:

TODO - SKY - DRY RUN

  name: ircc-kafka-cluster
  namespace: ircc-integration-amq-streams
spec:
  entityOperator:
    topicOperator:
      reconciliationIntervalSeconds: 60
      watchedNamespace: ircc-integration-amq-streams
    userOperator:
      reconciliationIntervalSeconds: 60
      watchedNamespace: ircc-integration-amq-streams
  kafka:
    config:
      inter.broker.protocol.version: '3.1'
      log.message.format.version: '3.1'
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-metrics
    resources:
      limits:
        cpu: '2'
        memory: 4Gi
      requests:
        cpu: '2'
        memory: 4Gi
    readinessProbe:
      initialDelaySeconds: 20
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 20
      timeoutSeconds: 5
    version: 3.1.0
    storage:
      size: 100Gi
      type: persistent-claim
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - authentication:
          type: tls
        configuration:
          bootstrap:
            host: kafka-bootstrap.apps.opc-hip-apps.aws.ci.gc.ca
          brokers:
            - broker: 0
              host: broker-0.apps.opc-hip-apps.aws.ci.gc.ca
            - broker: 1
              host: broker-1.apps.opc-hip-apps.aws.ci.gc.ca
            - broker: 2
              host: broker-2.apps.opc-hip-apps.aws.ci.gc.ca
        name: external
        port: 9094
        tls: true
        type: route
    logging:
      loggers:
        kafka.root.logger.level: INFO
      type: inline
  kafkaExporter:
    groupRegex: .*
    topicRegex: .*
  zookeeper:
    logging:
      loggers:
        zookeeper.root.logger: INFO
      type: inline
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper-metrics-config.yml
          name: kafka-metrics
    replicas: 3
    resources:
      limits:
        cpu: '2'
        memory: 4Gi
      requests:
        cpu: '2'
        memory: 4Gi
    storage:
      size: 100Gi
      type: persistent-claim
