apiVersion: argoproj.io/v1
kind: Application
metadata:
  name: namespace-config-operator
  namespace: openshift-gitops
spec:
  source:
    path: environments/dev/app/operators/overlays/namespace-config