apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: openshift-gitops
spec:
  source:
    path: environments/dev/app/namespaces/overlays
    targetRevision: HEAD
