kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: int-sandbox-constant-carmai

bases:
- ../../../../../../components/app/namespaces/small

resources:
- int-sandbox-constant-carmai.yaml

