kind: Namespace
apiVersion: v1
metadata:
  name: ircc-integration-sandbox-daniel-taylor
  labels:
    ircc.gc.ca/environment: dev
    ircc.gc.ca/team: ircc-integration
    argocd.argoproj.io/managed-by: tenant-integration-gitops 
spec: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: ircc-integration-sandbox-daniel-taylor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: Developers
