kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ircc-integration-amq-broker

bases:
- ../../../../../components/app/namespaces/medium

resources:
- ircc-integration-amq-broker.yaml


patches:
- target:
    kind: ResourceQuota
    name: project-quota
  patch: |-
    - op: replace
      path: /spec/hard/requests.storage
      value: '200G'