apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-broker-rhel8
  namespace: ircc-openshift-amq-broker
spec:
  channel: 7.x
  installPlanApproval: Manual
  name: amq-broker-rhel8
  source: redhat-operators
  sourceNamespace: openshift-marketplace
