kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
- namespace-ircc-integration-amq-broker.yaml
- amq-broker-operatorgroup.yaml
- github.com/davidgaulin/tmp-gitops-catalog/amq-broker-operator/overlays/amq-broker-7.x?tag=amq-broker-7.x-r1
- amq-broker-instance.yaml

patches:
- target:
    kind: Subscription
    name: amq-broker-rhel8
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: 'ircc-integration-amq-broker'
