kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunPOnMissingResource=true

resources:
- namespace-ircc-integration-amq-broker.yaml
- github.com/davidgaulin/tmp-gitops-catalog/amq-broker-operator/overlays/amq-broker-7.x?tag=amq-broker-7.x-r1
- amq-broker-operatorgroup.yaml
- amq-broker-instance.yaml
