kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ircc-eso-sandbox-sullivan-michael

bases:
- ../../../../../../components/app/namespaces/small

resources:
- ircc-eso-sandbox-sullivan-michael.yaml

