kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ircc-cicd

bases:
- ../../../../../../components/app/namespaces/small

resources:
- ircc-cicd.yaml

patches:
- patch-limits.yaml
