apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: openshift-gitops
spec:
  destination:
    namespace: ircc-tenant-integration-gitops
  source:
    path: environments/dev/app/tenants/integration/overlays/gitops
