kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
- ../../../../../../../components/argocd/apps/operators/gitops/base

patches:
- target:
    kind: Application
    name: argocd
  patch: |-
    - op: replace
      path: /metadata/name
      value: 'tenant-integration-gitops'

patchesStrategicMerge:
- gitops.yaml