apiVersion: v1
kind: ResourceQuota
metadata:
 name: project-quota
spec:
  hard:
    pods: "30" 
    requests.cpu: "1" 
    requests.memory: 2Gi 
    limits.cpu: "1" 
    limits.memory: 4Gi
    requests.storage: "20G"