apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: ircc-amq-broker
  namespace: ircc-openshift-amq-broker
spec:
  adminPassword: admin
  adminUser: admin
  console:
    expose: true
  deploymentPlan:
    size: 3
    persistenceEnabled: true
    messageMigration: true
    managementRBACEnabled: true
    journalType: nio
    enableMetricsPlugin: true
    image: 'registry.redhat.io/amq7/amq-broker:7.8'
    storage:
      size: 50Gi
  upgrades:
    enabled: false
    minor: false
  version: 7.8.6
