apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amq-broker-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  labels:
    gitops.ownedBy: cluster-config  
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: components/app/operators/amq-broker/base
    repoURL: 'https://github.com/filiy/gitops-test.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2 
        maxDuration: 3m 