kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
- yaks-operator-group.yaml
- github.com/davidgaulin/tmp-gitops-catalog/yaks/overlays/alpha?ref=HEAD

patches:
- target:
    kind: Subscription
    name: yaks
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: 'ircc-integration-testing'
